file:
  directory: D:/ksj/download/greengram_ver3

jwt-const:
  issuer: green@green.kr #토큰 발행자
  secret: DaeguGreenComputerAcademysmdfajlsfjlaskfjlaskdienvoinxovkaodlvikasjofiajsoidkjrfoeaiwjfo
  header-schema-name: Authorization
  claim-key: signedUser
  token-name: JWT
  token-type: Bearer
  access-token-expiry: 600_000 #10minuit (ms)
  refresh-token-expiry: 1_296_000_000 #15days (ms)
  refresh-token-cookie-name: refresh-token
  refresh-token-cookie-expiry: 1_296_000 #15days (s)

mybatis:
  mapper-locations: mappers/**/*.xml

spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost/jwt
    username: root
    password: green502

springdoc:
  swagger-ui:
    default-model-expand-depth: 10
    display-request-duration: true
    groups-order: asc
    operations-sorter: method
    path: /swagger
    tags-sorter: alpha
  cache:
    disabled: true