file:
  directory: D:/ksj/download/greengram_ver3

constant:
  info-const:
    title: JWT Practice
    description: JWT + Security 고도화
    version : v0.1

  jwt-const:
    issuer: green@green.kr #토큰 발행자
    secret: DaeguGreenComputerAcademysmdfajlsfjlaskfjlaskdienvoinxovkaodlvikasjofiajsoidkjrfoeaiwjfo
    header-key: Authorization
    claim-key: signedUser
    bearer-format: JWT
    scheme: Bearer
    access-token-expiry: 86_400_000 #24hour (ms)  #24*60*60*24*1000
    refresh-token-expiry: 1_296_000_000 #15days (ms)
    refresh-token-cookie-name: refresh-token
    refresh-token-cookie-expiry: 1_296_000 #15days (s)

mybatis:
  mapper-locations: mappers/**/*.xml

spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost/jwt
    username: root
    password: green502

springdoc:
  swagger-ui:
    default-model-expand-depth: 10
    display-request-duration: true
    groups-order: asc
    operations-sorter: method
    path: /swagger
    tags-sorter: alpha
  cache:
    disabled: true